// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgeneration.actions;

import java.util.List;
import mxmodelreflection.proxies.MxObjectType;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ReturnMxObjectType extends CustomJavaAction<IMendixObject>
{
	private IMendixObject MxObject;

	public ReturnMxObjectType(IContext context, IMendixObject MxObject)
	{
		super(context);
		this.MxObject = MxObject;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		String name = this.MxObject.getMetaObject().getName();
	
		List <IMendixObject> resultretrieve = Core.retrieveXPathQuery(this.getContext(), "//" + MxObjectType.getType() + "[" + MxObjectType.MemberNames.CompleteName.toString() + "='" +  name + "']");
		
		IMendixObject result = null;
		for (IMendixObject k : resultretrieve)
		{
			result = k;
			break;
		}
		return result;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ReturnMxObjectType";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
