// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package loginexample.actions;

import loginexample.CustomLoginAction;
import loginexample.CustomLoginActionListener;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class StartCustomLogin extends CustomJavaAction<java.lang.Boolean>
{
	public StartCustomLogin(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		CustomLoginActionListener listener = new CustomLoginActionListener();
		listener.addReplaceEvent(CustomLoginAction.class.getName());
		Core.addUserAction(CustomLoginAction.class);
		Core.getListenersRegistry().addListener(listener);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StartCustomLogin";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
