// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectcomparator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetObjectType extends CustomJavaAction<java.lang.String>
{
	private IMendixObject MxObject;

	public GetObjectType(IContext context, IMendixObject MxObject)
	{
		super(context);
		this.MxObject = MxObject;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if( this.MxObject != null ) 
			return this.MxObject.getType();
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetObjectType";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
