// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package versiondisplay.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;
import org.json.simple.parser.JSONParser;
import org.json.JSONObject;
import java.io.FileReader;
import java.net.URL;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * 
 */
public class MendixVersion extends CustomJavaAction<String>
{
	public MendixVersion(IContext context)
	{
		super(context);
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
//        JSONParser parser = new JSONParser();
//        URL resource = this.getClass().getClassLoader().getResource("translations.properties");
//        String path = resource.getPath().replace("lib/i18n/translations.properties", "metadata.json").replaceAll("%20", " ");
//
//        org.json.simple.JSONObject jsonObject = (org.json.simple.JSONObject)parser.parse(new FileReader(path));
//
//        JSONObject jobj = new JSONObject(jsonObject);
//
//        Core.getConfiguration().RUNTIME_VERSION gmetadata = new Metadata(jobj);

//        return metadata.getRuntimeVersion();

		return "";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "MendixVersion";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
