// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_library.actions;

import java.util.Calendar;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetDate extends CustomJavaAction<java.util.Date>
{
	private java.util.Date Day;
	private java.lang.Long Hour;
	private java.lang.Long Minute;
	private java.lang.Long Second;
	private java.lang.String TimeZone;

	public GetDate(IContext context, java.util.Date Day, java.lang.Long Hour, java.lang.Long Minute, java.lang.Long Second, java.lang.String TimeZone)
	{
		super(context);
		this.Day = Day;
		this.Hour = Hour;
		this.Minute = Minute;
		this.Second = Second;
		this.TimeZone = TimeZone;
	}

	@java.lang.Override
	public java.util.Date executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		if( java.util.TimeZone.getTimeZone(this.TimeZone) == null ) {
			Core.getLogger(this.toString()).error("Timezone: " + this.TimeZone+ " not found, setting timezone to: " + "US/Central");
			this.TimeZone= "US/Central";
		}
			
		
		Calendar cal = Calendar.getInstance(java.util.TimeZone.getTimeZone(this.TimeZone));
		
//		int tzOffset = TimeZone.getTimeZone(this.TimeZoneParameter1).getOffset(this.Day.getTime());
//		tzOffset = (tzOffset/3600000);
//		Core.getLogger(this.toString()).info(tzOffset +"");
		cal.setTime(this.Day);
		cal.set(Calendar.HOUR_OF_DAY, this.Hour.intValue());
//		cal.add(Calendar.HOUR_OF_DAY, tzOffset * -1);
		cal.set(Calendar.MINUTE, this.Minute.intValue() );
		cal.set(Calendar.SECOND, this.Second.intValue() );
		
		
		return cal.getTime();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetDate";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
