// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_library.actions;

import java.util.Calendar;
import java.util.TimeZone;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * 
 */
public class GetDate extends CustomJavaAction<java.util.Date>
{
	private java.util.Date Day;
	private Long Hour;
	private Long Minute;
	private Long Second;
	private String TimeZoneParameter1;

	public GetDate(IContext context, java.util.Date Day, Long Hour, Long Minute, Long Second, String TimeZoneParameter1)
	{
		super(context);
		this.Day = Day;
		this.Hour = Hour;
		this.Minute = Minute;
		this.Second = Second;
		this.TimeZoneParameter1 = TimeZoneParameter1;
	}

	@Override
	public java.util.Date executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		if( TimeZone.getTimeZone(this.TimeZoneParameter1) == null ) {
			Core.getLogger(this.toString()).error("Timezone: " + this.TimeZoneParameter1 + " not found, setting timezone to: " + "US/Central");
			this.TimeZoneParameter1 = "US/Central";
		}
			
		
		Calendar cal = Calendar.getInstance(TimeZone.getTimeZone(this.TimeZoneParameter1));
		
//		int tzOffset = TimeZone.getTimeZone(this.TimeZoneParameter1).getOffset(this.Day.getTime());
//		tzOffset = (tzOffset/3600000);
//		Core.getLogger(this.toString()).info(tzOffset +"");
		cal.setTime(this.Day);
		cal.set(Calendar.HOUR_OF_DAY, this.Hour.intValue());
//		cal.add(Calendar.HOUR_OF_DAY, tzOffset * -1);
		cal.set(Calendar.MINUTE, this.Minute.intValue() );
		cal.set(Calendar.SECOND, this.Second.intValue() );
		
		
		return cal.getTime();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetDate";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
