// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_library.actions;

import java_library.FTPConnector;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * 
 */
public class GetFileFromFTP extends CustomJavaAction<Boolean>
{
	private String ftpHostName;
	private String ftpUserName;
	private String ftpPassword;
	private String ftpRemoteDirectory;
	private Long ftpPort;
	private IMendixObject FileDocumentParameter1;

	public GetFileFromFTP(IContext context, String ftpHostName, String ftpUserName, String ftpPassword, String ftpRemoteDirectory, Long ftpPort, IMendixObject FileDocumentParameter1)
	{
		super(context);
		this.ftpHostName = ftpHostName;
		this.ftpUserName = ftpUserName;
		this.ftpPassword = ftpPassword;
		this.ftpRemoteDirectory = ftpRemoteDirectory;
		this.ftpPort = ftpPort;
		this.FileDocumentParameter1 = FileDocumentParameter1;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		FTPConnector connector = new FTPConnector(this.ftpHostName, this.ftpPort.intValue(), this.ftpUserName, this.ftpPassword);

		connector.connect();

		connector.downloadFile(getContext(), this.FileDocumentParameter1, this.ftpRemoteDirectory);
		connector.closeConnection();
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetFileFromFTP";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
