// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_library.actions;

import java_library.FTPConnector;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class GetFileFromFTP extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ftpHostName;
	private java.lang.String ftpUserName;
	private java.lang.String ftpPassword;
	private java.lang.String ftpRemoteDirectory;
	private java.lang.Long ftpPort;
	private IMendixObject FileDocument;

	public GetFileFromFTP(IContext context, java.lang.String ftpHostName, java.lang.String ftpUserName, java.lang.String ftpPassword, java.lang.String ftpRemoteDirectory, java.lang.Long ftpPort, IMendixObject FileDocument)
	{
		super(context);
		this.ftpHostName = ftpHostName;
		this.ftpUserName = ftpUserName;
		this.ftpPassword = ftpPassword;
		this.ftpRemoteDirectory = ftpRemoteDirectory;
		this.ftpPort = ftpPort;
		this.FileDocument = FileDocument;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		FTPConnector connector = new FTPConnector(this.ftpHostName, this.ftpPort.intValue(), this.ftpUserName, this.ftpPassword);

		connector.connect();

		connector.downloadFile(getContext(), this.FileDocument, this.ftpRemoteDirectory);
		connector.closeConnection();
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileFromFTP";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
