// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package java_library.actions;

import system.proxies.User;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetSessionForUser extends CustomJavaAction<java.lang.String>
{
	private IMendixObject UserParameter1;

	public GetSessionForUser(IContext context, IMendixObject UserParameter1)
	{
		super(context);
		this.UserParameter1 = UserParameter1;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		ISession session = Core.getActiveSession((String) UserParameter1.getValue(this.getContext(), User.MemberNames.Name.toString()));
		if( session == null ) {
		Core.getLogger(this.toString()).error("No session found for user: " + ((String) UserParameter1.getValue(this.getContext(), User.MemberNames.Name.toString())));
			return "";
		}
		
		return session.getId().toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetSessionForUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
