// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package audittrail.actions;

import audittrail.log.CreateLogObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * MdK 27/08/2010: This java action creates a log object of the input object. The current member values of this object are stored in the log. The reference between the log object and the input object is not set by default. You can do this in a microflow if needed.
 */
public class CreateLogRecordOfObject extends CustomJavaAction<IMendixObject>
{
	private IMendixObject AuditableObject;
	private IMendixObject AuditTrailSuperClassObject;

	public CreateLogRecordOfObject(IContext context, IMendixObject AuditableObject, IMendixObject AuditTrailSuperClassObject)
	{
		super(context);
		this.AuditableObject = AuditableObject;
		this.AuditTrailSuperClassObject = AuditTrailSuperClassObject;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMendixObject logObject = CreateLogObject.CreateAuditLogItems( this.AuditableObject, this.AuditTrailSuperClassObject, this.getContext() );
		
		return logObject;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "CreateLogRecordOfObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
